---

name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml
    with:
      run-build: true
      check-compose: true
      upload-release-archives: true
      upload-helm-chart: true
